version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
    environment:
      - APP_KEY=12heriuy44981723uyeye72ye872
      - APP_ENV=development
      - APP_DEBUG=true
      - APACHE_RUN_USER=apache-www-volume
      - APACHE_RUN_GROUP=apache-www-volume
      - UNSPLASH_ACCESS_KEY=vSMZ60Iy_sX5CpEtjsNNFynprCksC1u4bGeiNNLnTOA
      - UNSPLASH_SECRET_KEY=LwSUD86o4627nHqk1XNO15WUacfmyEiu9T_iUKA1yTE
